// <auto-generated />
using System;
using HealthApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthApi.Migrations
{
    [DbContext(typeof(HealthContext))]
    partial class HealthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthApi.Model.Ailment", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Id");

                    b.HasKey("Name");

                    b.HasIndex("Id");

                    b.ToTable("Ailments");
                });

            modelBuilder.Entity("HealthApi.Model.Medication", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Doses");

                    b.Property<int?>("Id");

                    b.HasKey("Name");

                    b.HasIndex("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("HealthApi.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthApi.Model.Ailment", b =>
                {
                    b.HasOne("HealthApi.Model.Patient")
                        .WithMany("Ailments")
                        .HasForeignKey("Id");
                });

            modelBuilder.Entity("HealthApi.Model.Medication", b =>
                {
                    b.HasOne("HealthApi.Model.Patient")
                        .WithMany("Medications")
                        .HasForeignKey("Id");
                });
#pragma warning restore 612, 618
        }
    }
}
